In [1]:
print("hello")

hello

In [2]:
f = open("../데이터파일/name.txt", "r", encoding="utf-8")
data = f.read()
print(data)
f.close()

맨유
맨시티
QPR
AT마드리드
1-1
1-2
1-3
1-4

In [3]:
f = open("../데이터파일/name.txt", "a", encoding="utf-8")
while True:
    team = input("팀 이름: ")

    if (not team):
        break

    f.write(team + "\n")
f.close()

In [4]:
%pip install pandas openpyxl

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (3.0.5)
Requirement already satisfied: openpyxl in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (3.1.5)
Requirement already satisfied: numpy>=2.3.3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/dgsw25/Library/Python/3.14/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: et-xmlfile in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in /Users/dgsw25/Library/Python/3.14/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [5]:
import pandas as pd
df = pd.read_excel("../데이터파일/my_grade.xlsx")
df.head()

   이름  1차 지필  2차 지필  3차 지필 등급
0  유비     92     88     95  A
1  관우     80     90     85  B
2  장비     84     84     67  C

In [6]:
add_df = pd.DataFrame([{
    "이름": "조자룡",
    "1차 지필": 63,
    "2차 지필": 75,
    "3차 지필": 84,
    "등급": "C",
}])

modi_file = pd.concat([df, add_df], ignore_index=True)
modi_file.to_excel("../데이터파일/new_grade.xlsx", index=False)

In [7]:
#연습하기
import pandas as pd
df = pd.read_excel("../데이터파일/club.xlsx")
df.head()

      학번   이름  학년     동아리  역할
0  10401  이민호   1  AI 연구부  부장
1  10405  박서연   1  AI 연구부  부원
2  10503  최지우   1  AI 연구부  부원

In [8]:
add_df = pd.DataFrame([{
    "학번": 10512,
    "이름": "김하늘",
    "학년": 1,
    "동아리": "AI 연구부",
    "역할": "부원"
}])

modi_file = pd.concat([df, add_df], ignore_index=True)
modi_file.to_excel("../데이터파일/new_club.xlsx", index=False)